CREATE TABLE responses
  (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    repository_url VARCHAR(255) NOT NULL,
    commits_count INT,
    open_pull_request_count INT,
    readme_url VARCHAR(255),
    readme_content TEXT,
    PRIMARY KEY (id)
  );

CREATE TABLE analysis_history
  (
     id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
     login_id    VARCHAR(255) NOT NULL,
     owner_name  VARCHAR(255) NOT NULL,
     repository_name   VARCHAR(255) NOT NULL,
     searched_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
     response_id BIGINT NOT NULL,
     PRIMARY KEY (id)
  );


