drop table users if exists;

CREATE TABLE users
  (
     id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
     email       VARCHAR(255) unique,
     image       VARCHAR(255),
     login_id    VARCHAR(255) NOT NULL unique,
     name        VARCHAR(255) NOT NULL,
     provider    VARCHAR(255) NOT NULL,
     provider_id VARCHAR(255),
     location VARCHAR(255),
     PRIMARY KEY (id)
  );


